In [103]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, r2_score, confusion_matrix, ConfusionMatrixDisplay
from sklearn.linear_model import LinearRegression
from sqlalchemy import create_engine

In [104]:
df_categorias = pd.read_csv('../data_lake/categorias.csv') #
df_clientes= pd.read_csv('../data_lake/clientes.csv') #
df_metod_pago = pd.read_csv('../data_lake/metodos_pago.csv') #
df_ventas = pd.read_csv('../data_lake/ventas.csv')
df_productos = pd.read_csv('../data_lake/productos.csv')

In [105]:
df_clientes.isna().sum()

ID_Cliente         0
Nombre             0
Apellido           0
Email              0
Fecha_Resgistro    0
Región             0
dtype: int64

In [106]:
df_categorias.isna().sum()

ID_Categoria    0
Categoría       0
Descripción     0
dtype: int64

In [107]:
df_metod_pago.isna().sum()

ID_Metodo      0
Método         0
Descripción    0
dtype: int64

In [108]:
df_ventas.isna().sum()

ID_Venta       0
Fecha          0
ID_Cliente     0
ID_Producto    0
Cantidad       0
Método_Pago    0
Estado         0
dtype: int64

In [109]:
df_productos.isna().sum()

ID_Producto        0
Nombre_producto    0
Categoría          0
Precio_Unitario    0
Stock              0
dtype: int64

In [110]:
df_clientes.columns

Index(['ID_Cliente', 'Nombre', 'Apellido', 'Email', 'Fecha_Resgistro',
       'Región'],
      dtype='object')

In [111]:
df_clientes.head(5)

,ID_Cliente,Nombre,Apellido,Email,Fecha_Resgistro,Región
0,1,Karisa,Cromett,kcromett0@imageshack.us,19/11/2023,Patagonia
1,2,Lenette,Seabert,lseabert1@yahoo.co.jp,07/05/2023,Patagonia
2,3,Buddy,Silverson,bsilverson2@howstuffworks.com,27/03/2023,Patagonia
3,4,Dan,Parkin,dparkin3@virginia.edu,26/10/2023,Buenos Aires
4,5,Conney,Cassella,ccassella4@who.int,31/03/2023,Centro

In [112]:
df_categorias.head(5)

,ID_Categoria,Categoría,Descripción
0,1,Lácteos,"Productos lácteos frescos y procesados, como l..."
1,2,Carnicería,"Carnes frescas y procesadas, como carne de vac..."
2,3,Panadería,"Productos horneados frescos, como pan, factura..."
3,4,Frutas y Verduras,"Frutas y verduras frescas, locales e importada..."
4,5,Congelados,"Productos congelados, como papas fritas, empan..."

In [113]:
df_metod_pago.head(5)

,ID_Metodo,Método,Descripción
0,1,Efectivo,"Pago en dinero en efectivo, sin intermediarios..."
1,2,Tarjeta de Crédito,Pago con tarjetas emitidas por bancos y financ...
2,3,Tarjeta de Débito,Pago con tarjetas que debitán directamente de ...
3,4,Mercado Pago,Plataforma de pagos online que permite realiza...
4,5,Transferencia,Pago realizado a través de una transferencia d...

In [114]:
df_productos.head(5)

   ID_Producto Nombre_producto Categoría Precio_Unitario  Stock
0            1           Leche   Lácteos           12,24   3327
1            2           Yogur   Lácteos            5,21   3358
2            3   Queso cremoso   Lácteos           17,23   3167
3            4   Queso rallado   Lácteos           19,23   2099
4            5         Manteca   Lácteos            5,65   4929

In [115]:
mapeo = df_categorias.set_index('Categoría')['ID_Categoria']
mapeo

Categoría
Lácteos                1
Carnicería             2
Panadería              3
Frutas y Verduras      4
Congelados             5
Bebidas                6
Galletitas y Snacks    7
Conservas              8
Name: ID_Categoria, dtype: int64

In [116]:
df_productos['ID_Categoria'] = df_productos['Categoría'].map(mapeo)

In [117]:
df_productos_n = df_productos.drop(columns='Categoría')

In [118]:
df_productos_n.head(7)

   ID_Producto Nombre_producto Precio_Unitario  Stock  ID_Categoria
0            1           Leche           12,24   3327             1
1            2           Yogur            5,21   3358             1
2            3   Queso cremoso           17,23   3167             1
3            4   Queso rallado           19,23   2099             1
4            5         Manteca            5,65   4929             1
5            6           Asado           28,56   5137             2
6            7         Chorizo           11,25   4068             2

In [119]:
df_ventas.head(10)

,ID_Venta,Fecha,ID_Cliente,ID_Producto,Cantidad,Método_Pago,Estado
0,919,31/01/2024,10,25,5,1,Completa
1,947,31/01/2024,106,5,1,4,Completa
2,1317,31/1/2024,235,25,3,3,Completa
3,1607,31/1/2024,114,15,5,1,Completa
4,2038,31/1/2024,132,2,5,4,Completa
5,2436,31/1/2024,282,3,3,1,Completa
6,2578,31/1/2024,201,31,6,3,Completa
7,448,01/02/2024,5,19,3,4,Pendiente
8,492,01/02/2024,114,29,6,4,Completa
9,1099,1/2/2024,282,28,1,4,Completa

In [144]:
df_ventas.columns

Index(['ID_Venta', 'Fecha', 'ID_Cliente', 'ID_Producto', 'Cantidad',
       'Método_Pago', 'Estado'],
      dtype='object')

In [147]:
df_ventas = df_ventas.rename(columns={
    'ID_Venta': 'id_venta',
    'Fecha': 'fecha',
    'ID_Cliente': 'id_cliente',
    'ID_Producto': 'id_producto',
    'Cantidad': 'cantidad',
    'Método_Pago': 'metodo_pago',
    'Estado': 'estado'
})

In [142]:
df_clientes = df_clientes.rename(columns={
    'ID_Cliente': 'id_cliente',
    'Nombre': 'nombre',
    'Apellido': 'apellido',
    'Email': 'email',
    'fecha_resgistro': 'fecha_registro',
    'Región': 'region'
})

In [120]:
df_categorias = df_categorias.rename(columns={
    'ID_Categoria': 'id_categoria',
    'Categoría': 'categoria',
    'Descripción': 'descripcion'
})

In [133]:
df_productos_n = df_productos_n.rename(columns={
    'ID_Producto': 'id_productos',
    'Nombre_producto': 'nombre_productos',
    'precio_Unitario': 'precio_unitario',
    'Stock': 'stock',
    'id_Categoria': 'id_categoria'
})

In [122]:
engine = create_engine('postgresql://postgres:Postg_anderzon@localhost:5432/mi_primera_bd')

try:
    df_categorias.to_sql(
        'categorias', 
        con=engine, 
        if_exists='append',  
        index=False,         
        method='multi'       
    )
    print("Carga exitosa")
except Exception as e:
    print(f"Error al cargar: {e}")

Error al cargar: (psycopg2.errors.UniqueViolation) llave duplicada viola restricción de unicidad «id_categoria_pk»
DETAIL:  Ya existe la llave (id_categoria)=(1).

[SQL: INSERT INTO categorias (id_categoria, categoria, descripcion) VALUES (%(id_categoria_m0)s, %(categoria_m0)s, %(descripcion_m0)s), (%(id_categoria_m1)s, %(categoria_m1)s, %(descripcion_m1)s), (%(id_categoria_m2)s, %(categoria_m2)s, %(descripcion_m2)s), (%(id_categoria_m3)s, %(categoria_m3)s, %(descripcion_m3)s), (%(id_categoria_m4)s, %(categoria_m4)s, %(descripcion_m4)s), (%(id_categoria_m5)s, %(categoria_m5)s, %(descripcion_m5)s), (%(id_categoria_m6)s, %(categoria_m6)s, %(descripcion_m6)s), (%(id_categoria_m7)s, %(categoria_m7)s, %(descripcion_m7)s)]
[parameters: {'id_categoria_m0': 1, 'categoria_m0': 'Lácteos', 'descripcion_m0': 'Productos lácteos frescos y procesados, como leche, yogur, queso y manteca.', 'id_categoria_m1': 2, 'categoria_m1': 'Carnicería', 'descripcion_m1': 'Carnes frescas y procesadas, como carne de vaca, cerdo, pollo y embutidos.', 'id_categoria_m2': 3, 'categoria_m2': 'Panadería', 'descripcion_m2': 'Productos horneados frescos, como pan, facturas, medialunas y tortas.', 'id_categoria_m3': 4, 'categoria_m3': 'Frutas y Verduras', 'descripcion_m3': 'Frutas y verduras frescas, locales e importadas, para consumo diario.', 'id_categoria_m4': 5, 'categoria_m4': 'Congelados', 'descripcion_m4': 'Productos congelados, como papas fritas, empanadas, pizzas y verduras congeladas.', 'id_categoria_m5': 6, 'categoria_m5': 'Bebidas', 'descripcion_m5': 'Bebidas de todo tipo, como agua, jugos, refrescos, cerveza, vino y bebidas espirituosas.', 'id_categoria_m6': 7, 'categoria_m6': 'Galletitas y Snacks', 'descripcion_m6': 'Productos de snack, como galletitas, papas chips, maníes y otros productos para merendar.', 'id_categoria_m7': 8, 'categoria_m7': 'Conservas', 'descripcion_m7': 'Productos alimenticios enlatados o envasados, como arroz, lentejas, garbanzos y atún.'}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [134]:
try:
    df_productos_n.to_sql(
        'productos', 
        con=engine, 
        if_exists='append',  
        index=False,         
        method='multi'       
    )
    print("Carga exitosa")
except Exception as e:
    print(f"Error al cargar: {e}")

Carga exitosa

In [138]:
try:
    df_metod_pago.to_sql(
        'metodos_pago', 
        con=engine, 
        if_exists='append',  
        index=False,         
        method='multi'       
    )
    print("Carga exitosa")
except Exception as e:
    print(f"Error al cargar: {e}")

Carga exitosa

In [143]:
try:
    df_clientes.to_sql(
        'clientes', 
        con=engine, 
        if_exists='append',  
        index=False,         
        method='multi'       
    )
    print("Carga exitosa")
except Exception as e:
    print(f"Error al cargar: {e}")

Carga exitosa

In [152]:
df_ventas.loc[680]

id_venta            1325
fecha          18/4/2024
id_cliente            89
id_producto           24
cantidad               6
metodo_pago            1
estado          Completa
Name: 680, dtype: object

In [157]:
duplicados = df_ventas.duplicated(subset=['id_venta']).sum()

In [165]:
duplicados = df_ventas[df_ventas.duplicated(subset=['id_venta'], keep=False)]
#print(duplicados.sort_values(by='id_venta'))

In [163]:
df_ventas = df_ventas.drop_duplicates(subset=['id_venta'], keep='first')

In [164]:
try:
    df_ventas.to_sql(
        'ventas', 
        con=engine, 
        if_exists='append',  
        index=False,         
        method='multi'       
    )
    print("Carga exitosa")
except Exception as e:
    print(f"Error al cargar: {e}")

Carga exitosa