$ Explorar y guardas data_set limpio, con nulos para el dashboard

In [12]:
import pandas as pd
df = pd.read_csv('../data_sets/credito.csv')

In [24]:
df.dtypes

id                         int64
default                    int64
idade                      int64
sexo                         str
dependentes                int64
escolaridade                 str
estado_civil                 str
salario_anual                str
tipo_cartao                  str
meses_de_relacionamento    int64
qtd_produtos               int64
iteracoes_12m              int64
meses_inativo_12m          int64
limite_credito               str
valor_transacoes_12m         str
qtd_transacoes_12m         int64
dtype: object

- ver las el n veces que aparece un X valor en las columnas (sirve para filtrado)

In [14]:
(df == "na").sum()

id                            0
default                       0
idade                         0
sexo                          0
dependentes                   0
escolaridade               1519
estado_civil                749
salario_anual              1112
tipo_cartao                   0
meses_de_relacionamento       0
qtd_produtos                  0
iteracoes_12m                 0
meses_inativo_12m             0
limite_credito                0
valor_transacoes_12m          0
qtd_transacoes_12m            0
dtype: int64

- Pasar valor a nulos reales

In [15]:
df.replace(["na", "NA", "N/A", "null"], pd.NA, inplace=True)
df.isna().sum()

id                            0
default                       0
idade                         0
sexo                          0
dependentes                   0
escolaridade               1519
estado_civil                749
salario_anual              1112
tipo_cartao                   0
meses_de_relacionamento       0
qtd_produtos                  0
iteracoes_12m                 0
meses_inativo_12m             0
limite_credito                0
valor_transacoes_12m          0
qtd_transacoes_12m            0
dtype: int64

In [16]:
df.head(2)

,id,default,idade,sexo,dependentes,escolaridade,estado_civil,salario_anual,tipo_cartao,meses_de_relacionamento,qtd_produtos,iteracoes_12m,meses_inativo_12m,limite_credito,valor_transacoes_12m,qtd_transacoes_12m
0,768805383,0,45,M,3,ensino medio,casado,$60K - $80K,blue,39,5,3,1,"12.691,51","1.144,90",42
1,818770008,0,49,F,5,mestrado,solteiro,menos que $40K,blue,44,6,2,1,"8.256,96","1.291,45",33

In [17]:
df['salario_anual'] = df['salario_anual'].str.replace('K', '000')
df['salario_anual'] = df['salario_anual'].str.replace('$', '')
df.head(10)

,id,default,idade,sexo,dependentes,escolaridade,estado_civil,salario_anual,tipo_cartao,meses_de_relacionamento,qtd_produtos,iteracoes_12m,meses_inativo_12m,limite_credito,valor_transacoes_12m,qtd_transacoes_12m
0,768805383,0,45,M,3,ensino medio,casado,60000 - 80000,blue,39,5,3,1,"12.691,51","1.144,90",42
1,818770008,0,49,F,5,mestrado,solteiro,menos que 40000,blue,44,6,2,1,"8.256,96","1.291,45",33
2,713982108,0,51,M,3,mestrado,casado,80000 - 120000,blue,36,4,0,1,"3.418,56","1.887,72",20
3,769911858,0,40,F,4,ensino medio,NaN,menos que 40000,blue,34,3,1,4,"3.313,03","1.171,56",20
4,709106358,0,40,M,3,sem educacao formal,casado,60000 - 80000,blue,21,5,0,1,"4.716,22","816,08",28
5,713061558,0,44,M,2,mestrado,casado,40000 - 60000,blue,36,3,2,1,"4.010,69","1.088,07",24
6,810347208,0,51,M,4,NaN,casado,120000 +,gold,46,6,3,1,"34.516,72","1.330,87",31
7,818906208,0,32,M,0,ensino medio,NaN,60000 - 80000,silver,27,2,2,2,"29.081,49","1.538,32",36
8,710930508,0,37,M,3,sem educacao formal,solteiro,60000 - 80000,blue,36,5,0,2,"22.352,50","1.350,14",24
9,719661558,0,48,M,2,mestrado,solteiro,80000 - 120000,blue,36,6,3,3,"11.656,41","1.441,73",32

In [18]:
df.sexo.str.upper

In [25]:
df.dtypes

id                         int64
default                    int64
idade                      int64
sexo                         str
dependentes                int64
escolaridade                 str
estado_civil                 str
salario_anual                str
tipo_cartao                  str
meses_de_relacionamento    int64
qtd_produtos               int64
iteracoes_12m              int64
meses_inativo_12m          int64
limite_credito               str
valor_transacoes_12m         str
qtd_transacoes_12m         int64
dtype: object

In [ ]:
df['valor_transacoes_12m'] = df['valor_transacoes_12m'].str.replace('.', '')
df['valor_transacoes_12m'] = df['valor_transacoes_12m'].str.replace(',', '.')

In [33]:
df['limite_credito'] = df['limite_credito'].str.replace('.', '')
df['limite_credito'] = df['limite_credito'].str.replace(',', '.')

In [34]:
df.head(5)

,id,default,idade,sexo,dependentes,escolaridade,estado_civil,salario_anual,tipo_cartao,meses_de_relacionamento,qtd_produtos,iteracoes_12m,meses_inativo_12m,limite_credito,valor_transacoes_12m,qtd_transacoes_12m
0,768805383,0,45,M,3,ensino medio,casado,60000 - 80000,blue,39,5,3,1,12691.51,1144.90,42
1,818770008,0,49,F,5,mestrado,solteiro,menos que 40000,blue,44,6,2,1,8256.96,1291.45,33
2,713982108,0,51,M,3,mestrado,casado,80000 - 120000,blue,36,4,0,1,3418.56,1887.72,20
3,769911858,0,40,F,4,ensino medio,NaN,menos que 40000,blue,34,3,1,4,3313.03,1171.56,20
4,709106358,0,40,M,3,sem educacao formal,casado,60000 - 80000,blue,21,5,0,1,4716.22,816.08,28

In [39]:
df['valor_transacoes_12m'] = df['valor_transacoes_12m'].astype(float)
df['limite_credito'] = df['limite_credito'].astype(float)

In [40]:
df.dtypes

id                           int64
default                      int64
idade                        int64
sexo                           str
dependentes                  int64
escolaridade                   str
estado_civil                   str
salario_anual                  str
tipo_cartao                    str
meses_de_relacionamento      int64
qtd_produtos                 int64
iteracoes_12m                int64
meses_inativo_12m            int64
limite_credito             float64
valor_transacoes_12m       float64
qtd_transacoes_12m           int64
dtype: object

In [41]:
df.to_excel('..\data_Sets\datos_limpios.xlsx', index=False, sheet_name='hoja_1')

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Anderzon\AppData\Local\Temp\ipykernel_14636\1732220200.py:1: SyntaxWarning: invalid escape sequence '\d'
  df.to_excel('..\data_Sets\datos_limpios.xlsx', index=False, sheet_name='hoja_1')